version: '3.8'

services:
  document-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    container_name: document-management-app
    restart: unless-stopped
